# Generated by Django 3.1.1 on 2020-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('appid', models.IntegerField(help_text='AppID', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='游戏名', max_length=50)),
                ('has_card', models.BooleanField(help_text='有无卡牌')),
                ('p_current', models.IntegerField(help_text='当前价格*100')),
                ('p_origin', models.IntegerField(help_text='原始价格*100')),
                ('p_lowest', models.IntegerField(help_text='史低价格*100')),
                ('p_lowcut', models.IntegerField(help_text='史低折扣%')),
                ('p_cut', models.IntegerField(help_text='当前折扣%')),
                ('addtime', models.DateField(help_text='添加时间')),
                ('lowtime', models.DateField(help_text='史低时间')),
                ('updatetime', models.DateField(help_text='更新时间')),
                ('nexttime', models.DateField(help_text='下次更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Plainid',
            fields=[
                ('appid', models.IntegerField(help_text='AppID', max_length=8, primary_key=True, serialize=False, unique=True)),
                ('plainid', models.CharField(help_text='PlainID', max_length=50, unique=True)),
            ],
        ),
    ]
