# Generated by Django 3.1.4 on 2020-12-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='audlt',
            field=models.BooleanField(default=False, help_text='是否被标记为仅限成人', verbose_name='“仅限成人'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='ready',
            field=models.BooleanField(default=False, help_text='数据是否可用', verbose_name='可用'),
        ),
    ]
