# Generated by Django 3.1.4 on 2020-12-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.CharField(default='', help_text='公司备注', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, help_text='公司名称', max_length=100, unique=True, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='gtype',
            field=models.CharField(choices=[('', '-'), ('G', 'Game'), ('S', 'Software'), ('D', 'DLC'), ('V', 'Video')], default='', help_text='商店分类', max_length=1, verbose_name='类型'),
        ),
    ]
