# Generated by Django 3.1.1 on 2020-12-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='addtime',
            field=models.DateTimeField(help_text='添加时间'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='lowtime',
            field=models.DateTimeField(help_text='史低时间'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='nexttime',
            field=models.DateTimeField(help_text='下次更新时间'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='updatetime',
            field=models.DateTimeField(help_text='更新时间'),
        ),
    ]
