# Generated by Django 3.1.4 on 2020-12-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='公司备注', max_length=50, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, help_text='公司名称', max_length=50, unique=True, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='adult',
            field=models.BooleanField(default=False, help_text='是否被标记为仅限成人', verbose_name='仅限成人'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(db_index=True, help_text='标签中文名', max_length=50, unique=True, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name_en',
            field=models.CharField(db_index=True, help_text='标签英文名', max_length=50, unique=True, verbose_name='英文名'),
        ),
    ]
