# Generated by Django 3.1.1 on 2020-12-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='time',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cerror',
            field=models.IntegerField(default=0, help_text='出错计数器', verbose_name='出错'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cupdate',
            field=models.IntegerField(default=0, help_text='更新计数器', verbose_name='更新'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='cview',
            field=models.IntegerField(default=0, help_text='访问计数器', verbose_name='访问'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='pcurrent',
            field=models.IntegerField(default=-1, help_text='当前价格 * 100', verbose_name='现价'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='pcut',
            field=models.IntegerField(default=0, help_text='当前折扣,0:未打折', verbose_name='当前折扣%'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='plowest',
            field=models.IntegerField(default=-1, help_text='史低价格 * 100', verbose_name='史低'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='plowestcut',
            field=models.IntegerField(default=0, help_text='史低折扣,0:未打折', verbose_name='史低折扣%'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='porigin',
            field=models.IntegerField(default=-1, help_text='原始价格 * 100', verbose_name='原价'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tadd',
            field=models.IntegerField(default=0, help_text='添加时间戳', verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tlowest',
            field=models.IntegerField(default=0, help_text='史低时间戳', verbose_name='史低时间'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tmodify',
            field=models.IntegerField(default=0, help_text='上次修改时间戳', verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='trelease',
            field=models.IntegerField(default=0, help_text='游戏发行时间戳', verbose_name='发行时间'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tupdate',
            field=models.IntegerField(db_index=True, default=0, help_text='下次更新时间戳', verbose_name='更新时间'),
        ),
        migrations.DeleteModel(
            name='GamePriceInfo',
        ),
        migrations.DeleteModel(
            name='GameStatusInfo',
        ),
        migrations.DeleteModel(
            name='GameTimeInfo',
        ),
    ]
