# Generated by Django 3.1.4 on 2020-12-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaddlist',
            name='cerror',
            field=models.IntegerField(default=0, help_text='出错次数', verbose_name='出错次数'),
        ),
    ]
