# Generated by Django 3.1.4 on 2020-12-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='audlt',
            new_name='adult',
        ),
    ]
