# Generated by Django 3.1.4 on 2020-12-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='tupdate',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tuinfo',
            field=models.IntegerField(default=0, help_text='下次更新基本信息的时间戳', verbose_name='信息更新时间'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tuprice',
            field=models.IntegerField(db_index=True, default=0, help_text='下次更新价格信息的时间戳', verbose_name='价格更新时间'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='tmodify',
            field=models.IntegerField(db_index=True, default=0, help_text='最后一次爬取的时间戳', verbose_name='修改时间'),
        ),
    ]
