# Generated by Django 3.1.4 on 2020-12-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201221_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='name',
            field=models.CharField(default='', help_text='游戏英文名', max_length=150, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='name_cn',
            field=models.CharField(default='', help_text='游戏中文名', max_length=150, verbose_name='中文名'),
        ),
    ]
