# Generated by Django 3.1.4 on 2020-12-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gameaddlist_cerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebanlist',
            name='cerror',
            field=models.IntegerField(default=0, help_text='出错次数', verbose_name='出错次数'),
        ),
        migrations.AlterField(
            model_name='gameaddlist',
            name='cview',
            field=models.IntegerField(default=0, help_text='访问次数', verbose_name='访问次数'),
        ),
    ]
