# Generated by Django 3.1.1 on 2020-12-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201214_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='develop',
            field=models.ManyToManyField(blank=True, help_text='开发商', related_name='develop', to='app.Company', verbose_name='开发商'),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='publish',
            field=models.ManyToManyField(blank=True, help_text='发行商', related_name='publish', to='app.Company', verbose_name='发行商'),
        ),
    ]
