# Generated by Django 3.1.4 on 2020-12-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201217_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name_en',
            field=models.CharField(db_index=True, help_text='标签英文名', max_length=20, unique=True, verbose_name='英文名'),
        ),
    ]
