# Generated by Django 3.1.1 on 2020-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201211_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='r_percent',
            field=models.IntegerField(help_text='好评率', null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='r_score',
            field=models.IntegerField(help_text='评测分数0-10', null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='r_total',
            field=models.IntegerField(help_text='评测总人数', null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tags',
            field=models.TextField(help_text='标签', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='addtime',
            field=models.IntegerField(help_text='添加时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='appid',
            field=models.IntegerField(help_text='AppID', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='has_card',
            field=models.BooleanField(help_text='有无卡牌', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='lowtime',
            field=models.IntegerField(help_text='史低时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='nexttime',
            field=models.IntegerField(help_text='下次更新时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='p_current',
            field=models.IntegerField(help_text='当前价格*100', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='p_cut',
            field=models.IntegerField(help_text='当前折扣%', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='p_lowcut',
            field=models.IntegerField(help_text='史低折扣%', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='p_lowest',
            field=models.IntegerField(help_text='史低价格*100', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='p_origin',
            field=models.IntegerField(help_text='原始价格*100', null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='updatetime',
            field=models.IntegerField(help_text='更新时间戳', null=True),
        ),
        migrations.AlterField(
            model_name='plainid',
            name='appid',
            field=models.IntegerField(help_text='AppID', primary_key=True, serialize=False, unique=True),
        ),
    ]
