# Generated by Django 3.1.4 on 2020-12-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201221_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessstats',
            name='ip',
            field=models.CharField(db_index=True, help_text='访问IP', max_length=50, unique=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='company',
            name='desc',
            field=models.CharField(default='', help_text='公司备注', max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, help_text='公司名称', max_length=200, unique=True, verbose_name='公司名'),
        ),
    ]
