# Generated by Django 3.1.4 on 2020-12-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201217_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_index=True, help_text='公司名称', max_length=20, unique=True, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(db_index=True, help_text='标签中文名', max_length=20, unique=True, verbose_name='中文名'),
        ),
    ]
