# Generated by Django 3.1.1 on 2020-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201211_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='tags',
            field=models.CharField(help_text='标签', max_length=100, null=True),
        ),
    ]
