# Generated by Django 3.1.4 on 2020-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201221_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(help_text='标签英文名', max_length=50, verbose_name='英文名'),
        ),
    ]
